# Main plugin configuration
# DO NOT PUT YOUR API KEY HERE! Use plugin.local.yaml instead
# Copy plugin.local.yaml.example to plugin.local.yaml and add your API key there

ApiKey: "" # Will be loaded from plugin.local.yaml or environment variable SONARR_API_KEY
ServerUrl: "localhost:8989"
UseHttps: false 